# Generated by Django 4.2 on 2023-05-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('total', models.IntegerField()),
                ('avg', models.CharField()),
                ('max', models.FloatField()),
                ('min', models.CharField()),
                ('sumD', models.IntegerField()),
            ],
        ),
    ]
